visualization:
    use_visdom: True
    visdom_port: 9007
    visdom_server: 'http://localhost'

    image:
        every: 100
        scale: 1

model:
    net: 'tu-efficientnetv2_s'
    input_channels: 3
    model_classes: 2

dataset:
    train_images_path: 'PATH_TO_IMAGES_FOLDER'
    train_masks_path: 'PATH_TO_IMAGES_MASKS'
    test_images_path: 'PATH_TO_IMAGES_FOLDER'
    test_masks_path: 'PATH_TO_IMAGES_MASKS'
    shape: [256, 256]
    use_augmentations: True

train:
    lr: 0.001
    max_lr: -1
    weight_decay: 0

    gradient_accumulation_steps: 4

    epochs: 5000
    batch_size: 1
    num_workers: 4

    augmentation: True

    use_apex: False

    save:
        model: './experiments/MANet_efficientnetv2_s_256/'

    load: True
    load_optimizer: True