visualization:
    use_visdom: True
    visdom_port: 9007
    visdom_server: 'http://localhost'

    image:
        every: 100
        scale: 1

    use_tensorboard: False
    tensorboard_logdir: ''
    save_historgam: False

model:
    net: 'resnet50'
    input_channels: 3
    model_classes: 2

dataset:
    train_images_path: '/media/alexey/HDDDataDIsk/datasets/RetinalVesselSegmentation/CompetitionDataset/segmentation_representation/train/images/'
    train_masks_path: '/media/alexey/HDDDataDIsk/datasets/RetinalVesselSegmentation/CompetitionDataset/segmentation_representation/train/masks/'
    test_images_path: '/media/alexey/HDDDataDIsk/datasets/RetinalVesselSegmentation/CompetitionDataset/segmentation_representation/val/images/'
    test_masks_path: '/media/alexey/HDDDataDIsk/datasets/RetinalVesselSegmentation/CompetitionDataset/segmentation_representation/val/masks/'
#    train_images_path: '/media/alexey/HDDDataDIsk/datasets/RetinalVesselSegmentation/CHASE_DB1/HRF/images/'
#    train_masks_path: '/media/alexey/HDDDataDIsk/datasets/RetinalVesselSegmentation/CHASE_DB1/HRF/manual1/'
#    test_images_path: '/media/alexey/HDDDataDIsk/datasets/RetinalVesselSegmentation/CHASE_DB1/DRIVE/training/images/'
#    test_masks_path: '/media/alexey/HDDDataDIsk/datasets/RetinalVesselSegmentation/CHASE_DB1/DRIVE/training/1st_manual/'
    shape: [256, 256]   # [width, height]
    use_augmentations: True

train:
    optimizer: 'RAdam'
    lr: 0.001
    max_lr: -1
    weight_decay: 0

    gradient_accumulation_steps: 8

    epochs: 5000
    batch_size: 1
    num_workers: 4

    augmentation: True

    distribution_learning:
        enable: False
        devices: ['cuda:0', 'cuda:1']

    use_apex: False

    save:
        model: '/media/alexey/SSDDataDisk/experiments/RetinalVesselSegmentation/CompetitionDatasetTiling/MANet_resnet50_256/'
        every: 1

    load: True
    load_optimizer: True

    checkpoint:
        use: False
        model: ''
        optimizer: ''

logging:
    use_logger: False
    log_path: ''
    log_step: 1
